# FlakeHell is a flake8 wrapper which adds features like having a baseline
# https://github.com/flakehell/flakehell
name: FlakeHell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Install dependencies
        run: poetry install
      - name: Run FlakeHell
        run: poetry run flakehell lint
