# FlakeHell is a flake8 wrapper which adds features like having a baseline
# https://github.com/flakehell/flakehell
name: FlakeHell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install flake8
        # Flake8 4 doesn't work with FlakeHell so we have pin the version
        run: python -m pip install 'flake8==3.8' flakehell
      - name: Run FlakeHell
        run: flakehell lint
